#OBJS specifies which files to compile as part of the project
OBJS = src/*.cpp
# g++ *.cpp -std=c++11 -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -llua5.3 -o 01_hello_SDL

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = mote_Run

#This is the target that compiles our executable
all : $(OBJS)
	g++ $(OBJS) -std=gnu++11 -w -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -llua5.3 -Box2D -o $(OBJ_NAME)















